spring.application.name=backend-werb-mr
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=${JWT_SECRET:clave-super-secreta-para-firmar-tokens-jwt-de-desarrollo}
app.jwt.expiracion-ms=${JWT_EXPIRACION_MS:86400000}
app.admin.nombre=${ADMIN_NOMBRE:Cristhian David}
app.admin.correo=${ADMIN_CORREO:cristhian.david@admin.com}
app.admin.contrasena=${ADMIN_CONTRASENA:Cdol1122@}
